import type { Metadata } from "next";

import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, } from "@clerk/nextjs";
import HomePage from "@/components/Home";
import { ResourceProvider } from "@/context/ResourceContext";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
        <Toaster position="top-right" />
        <SignedOut>
            <HomePage /> 
          </SignedOut>
          <SignedIn>
            <ResourceProvider>
              {children}
            </ResourceProvider>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  )
}
