import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton } from "@clerk/nextjs";
import HomePage from "@/components/Home";
import { ResourceProvider } from "@/context/ResourceContext";
import { Toaster } from "react-hot-toast";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
        <Toaster position="top-right" />
        <SignedOut>
            <HomePage /> 
          </SignedOut>
          <SignedIn>
            <ResourceProvider>
              {children}
            </ResourceProvider>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  )
}
